spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./db/app;AUTO_SERVER=TRUE
    username: root
    password: qwerty
  application:
    name: ToDoAPI
  liquibase:
    change-log: classpath:db/changelog/master.yaml
